# 03-load-generator.yaml
apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: hpa-demo
spec:
  containers:
  - name: load
    image: busybox:1.36
    command:
    - /bin/sh
    - -c
    - "while true; do wget -q -O- http://php-apache; done"
  restartPolicy: Never
