# 04-app2-service.yaml
# ClusterIP service for App 2
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  labels:
    app: app2
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
