# 03-pod-reader-binding.yaml
# RoleBinding to grant pod-reader Role to app-reader ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: rbac-demo
  labels:
    app: rbac-demo
subjects:
# Reference to ServiceAccount
- kind: ServiceAccount
  name: app-reader
  namespace: rbac-demo
roleRef:
  # Reference to Role
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
